### ISSUE TITLE
What is the preferred way for agents to access past stocks or transactions?

### ISSUE THREAD

**Issue by riktross** [fuadlabgit/sfctools#2]
Hello!

I am trying build a simple SFC model to learn how to use sfctools. In it, consumption of household agents during period t depends on the stock of money held at the end of period t-1.

The agent class allows me to access current balance sheets, but as far as I understand does not keep a history of transactions that I can use to access past stocks or flows.

The best way I can think about implementing this would be to store the history of the variable in the main loop, then calculate the quantity consumed in the `iter()` function, outside the agent object, and passing the quantity as an argument to the transaction function defined in the agent. Is that indeed the best approach?

Thank you in advance for any insight!

**Comment by fuadlabgit** [comment]
Hello @riktross thank you very much for creating this issue! As far as I am concerned, this is the first issue by an external user. 

I guess your intuition was quite right here. It is best to store the quantity in some other kind of data structure. In the example, I used a list to just store all the data from the balance sheet in all the time steps. An alternative version could be to just store the required data for [t-1] and overwrite it every time you increase t.

I admit that it's kind of fiddly to modify the balance sheet. I have set up an example code for you (hope this works in your installed version). In this example, I just used the attribute 'history' to store the information within the ExampleAgent object itself (so no need to store it externally). Storing the history externally is of course another option that would work just as fine.

```
from sfctools import Agent, BalanceEntry
import numpy as np 

class ExampleAgent(Agent):
    def __init__(self):
        super().__init__()
        self.history = []  # <- this will store the entire balance sheet data history

    def change_balance_sheet(self, x):

        self.history.append(self.balance_sheet.raw_data) # <- copy the current data 
        
        # call whatever transaction here... 
        with self.balance_sheet.modify: # add x of 'ExampleAsset' to balance sheet
            self[("ExampleAssets", BalanceEntry.ASSETS)] += x
            self[("ExampleLiabilities", BalanceEntry.LIABILITIES)] += x 
        
    def file_bankruptcy(self, event):
        pass 

# create an example agent
a = ExampleAgent()

# define an iteration loop
def iter():
    random_number = np.random.rand()
    a.change_balance_sheet(random_number)

# run 10 iterations
for i in range(10):
    iter()

# read out balance of 'ExampleAsset'
hist_data = [h["ExampleAssets"][BalanceEntry.ASSETS] for h in a.history] # < read out the data from the history
print(hist_data)
```

Please let me know if it works, otherwise do not hesitate to comment again


In your case, 

`self.history = self[("ExampleAssets", BalanceEntry.ASSETS)]`
would suffice probably.

The intuition behind this design is computational resources: storing all stocks and flows quantities from all agents can quickly blow up your memory if there are many interacting agents...

**Comment by fuadlabgit** [comment]
EDIT: I used ver 1.1.9.2 (the latest up to date) for the above example

**Comment by erik-rossbach** [comment]
Thanks a lot for responding so quickly! The script you sent worked on my end, thanks a lot! 

PS: Happy to be the first issue poster, this is a really great project :) the GUI makes designing the accounting really painless

**Comment by fuadlabgit** [comment]
Thank you, too. Feature requests and bug reports welcome :) also on the gitlab site https://gitlab.com/dlr-ve/esy/sfctools/framework
